version: '3'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: laravel_php
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: laravel_nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        container_name: laravel_mysql
        image: mysql:8.0
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: '<root-password>'
            MYSQL_DATABASE: helloworld
            MYSQL_USER: helloworld
            MYSQL_PASSWORD: '<db-password>'

    # ####################################################################################################
    # # PHPMYADMIN
    # ####################################################################################################
    phpmyadmin:
        container_name: laravel_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: '<root-password>'
        depends_on:
            - db